---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-clusterio-slave1
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio-slave1
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio-slave1
    spec:
      volumes:
        - name: factorio-clusterio-persistent-storage-slave1
          persistentVolumeClaim:
            claimName: factorio-clusterio-pv-claim-slave1
      containers:
        - name: factorio-slave1
          image: mcweezel/factorio-clusterio:latest
          imagePullPolicy: Always
          ports:
            - name: game-port
              containerPort: 34197
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - mountPath: /factorio
              name: factorio-clusterio-persistent-storage-slave1
        - name: factorio-clusterio-sidecar-slave1
          image: mcweezel/factorio-clusterio:latest
          command:
            - sh
            - -c
            - "cd /factorio/factorioClusterio && node slave.js"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 128Mi
          volumeMounts:
            - mountPath: /factorio
              name: factorio-clusterio-persistent-storage-slave1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-clusterio-persistent-storage-slave1
  labels:
    app: factorio-clusterio-slave1
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
