---
apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-clusterio-configmap-22222
data:
  config.json: | 
    {
        "__comment": "Where factorio folder. Should be in the same folder as this config file.",
        "factorioDirectory": "./factorio",
        "instanceDirectory": "./instances",
        "databaseDirectory": "./database",
        "__comment1": "IP players should connect to to join your servers, should be portforwarded and stuff",
        "publicIP": "kubx.weezel.work",
        "__comment2": "IP the master web server runs at, can be ignored on the master system",
        "masterIP": "factorio-clusterio-master",
        "__commentMasterPort": "HTTP port for the master to listen to",
        "masterPort": 8080,
        "__commentsslPort": "HTTPS port for the master to listen to. Set to 0 or an empty string to not listen for HTTPS.",
        "sslPort": 443,
        "sslCert": "database/certificates/cert.crt",
        "sslPrivKey": "database/certificates/cert.key",
        "__commentMasterAuthToken": "Authentication token to connect to the master server. Find it in secret-api-token.txt on the master.",
        "masterAuthToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFwaSIsImlhdCI6MTU1NDc2OTEzMSwiZXhwIjoxNTg2MzA1MTMxfQ.MYvma8iP8F00pVaGcXEfw4P3dU7PqPtyEIJXuv7Xq7E",
        "__commentAuthSecret": "This is a long random string used for generating authentication tokens. Do not share. Regenerates when secret-api-token.txt is deleted.",
        "masterAuthSecret": "OsS9i3t0PQ_xB7mojihiqvQwa0tNQZWNonhXjGxn5yaZRPLhMB_32nl83wXAh9h5-TwjVfOM4g4TBbnpTP5oxM5UXqjLvWP83ClCt-o8vwtZ03EMf5H8e89SddAEuwFpLSZfoTJFEMZIX79HXQ5sbRUqfUPq8JQqaI_GOf-eZCB1uCzKfRTvaJhj1LZtTlhFBMVHHNM0dEedOsxkEioTN8PlYDrNhgfm_Bu5Io7C0FzkDmjGeNlan8Xw2C35uF4_sSsYNBPu1eT5dU2CO2Nm1VKbd56pWGnOLQ-ZLhMBQmuyAVveqkooG5FDdBSZonU-UQe6YLJ0mS5WWhcNinU9vw",
        "__comment3": "Your factorio.com username for factorio MP services, also username will be admin on new instances",
        "username": "MC_Weezel",
        "__comment4": "Token from your factorio.com profile page. Required for MP and mod manager services.",
        "token": "c5a64c18fd72138818648632ae7574",
        "__comment7": "Autosave interval for items in the master storage in milliseconds. Defaults to one minute when set to 0 or not set.",
        "factorio_version": "1.17.31",
        "__comment5": "General user settings",
        "verify_user_identity": true,
        "auto_pause": false,
        "allow_commands": "admins-only",
        "game_password": "thisisagreatpassword",
        "description": "MC_Weezel Clusterio",
        "visibility": {
            "public": true,
            "lan": true
        },
        "__comment6": "Statistic gathering statistics, may affect server performance (master memory usage especially)",
        "itemStats": {
            "maxEntries": 60,
            "entriesPerSecond": 0.01666666667
        },
        "logItemTransfers": false,
        "__comment6.5": "When the master is undersupplied, we have 3 different modes to 'fairly' distribute items. First to ask gets all, dole division using weird formula or experimental neural net tries to make stuff as fair as possible. Feel free to play around.",
        "disableFairItemDistribution": false,
        "useNeuralNetDoleDivider": false,
        "uploadModsToMaster": true,
        "msBetweenCommands": 10,
        "allowRemoteCommandExecution": true,
        "enableCrossServerShout": true,
        "mirrorAllChat": false,
        "autosaveInterval": 600000,
        "disablePrometheusPushgateway": false,
        "__comment8": "This setting only affects the master. It makes every import for things that arent 'electricity' return a maximum of 0. Effectively disables teleport chests.",
        "disableImportsOfEverythingExceptElectricity": false
    }
  instanceconfig.json: |
    {
        "factorioPort": 34197,
        "clientPort": 8080,
        "__comment_clientPassword": "This is the rcon password. Its also used for making an instanceID. Make sure its unique and not blank.",
        "clientPassword": "allthecheeseburgers"
    }
  server-settings.json: |
    {
      "name": "My totally awesome game",
      "description": "This thing is totally awesome",
      "tags": ["totally", "awesome"],
    
      "_comment_max_players": "Maximum number of players allowed, admins can join even a full server. 0 means unlimited.",
      "max_players": 0,
    
      "_comment_visibility": ["public: Game will be published on the official Factorio matching server",
                              "lan: Game will be broadcast on LAN"],
      "visibility":
      {
        "public": true,
        "lan": true
      },
    
      "_comment_credentials": "Your factorio.com login credentials. Required for games with visibility public",
      "username": "MC_Weezel",
      "password": "",
    
      "_comment_token": "Authentication token. May be used instead of 'password' above.",
      "token": "c5a64c18fd72138818648632ae7574",
    
      "game_password": "PASSWORD",
    
      "_comment_require_user_verification": "When set to true, the server will only allow clients that have a valid Factorio.com account",
      "require_user_verification": true,
    
      "_comment_max_upload_in_kilobytes_per_second" : "optional, default value is 0. 0 means unlimited.",
      "max_upload_in_kilobytes_per_second": 0,
    
      "_comment_minimum_latency_in_ticks": "optional one tick is 16ms in default speed, default value is 0. 0 means no minimum.",
      "minimum_latency_in_ticks": 0,
    
      "_comment_ignore_player_limit_for_returning_players": "Players that played on this map already can join even when the max player limit was reached.",
      "ignore_player_limit_for_returning_players": false,
    
      "_comment_allow_commands": "possible values are, true, false and admins-only",
      "allow_commands": "admins-only",
    
      "_comment_autosave_interval": "Autosave interval in minutes",
      "autosave_interval": 10,
    
      "_comment_autosave_slots": "server autosave slots, it is cycled through when the server autosaves.",
      "autosave_slots": 5,
    
      "_comment_afk_autokick_interval": "How many minutes until someone is kicked when doing nothing, 0 for never.",
      "afk_autokick_interval": 0,
    
      "_comment_auto_pause": "Whether should the server be paused when no players are present.",
      "auto_pause": true,
    
      "only_admins_can_pause_the_game": true,
    
      "_comment_autosave_only_on_server": "Whether autosaves should be saved only on server or also on all connected clients. Default is true.",
      "autosave_only_on_server": true,
    
      "_comment_non_blocking_saving": "Highly experimental feature, enable only at your own risk of losing your saves. On UNIX systems, server will fork itself to create an autosave. Autosaving on connected Windows clients will be disabled regardless of autosave_only_on_server option.",
      "non_blocking_saving": false,
    
      "_comment_admins": "List of case insensitive usernames, that will be promoted immediately",
      "admins": []
    }
  map-gen-settings.json: |
    {
      "_terrain_segmentation_comment": "Inverse of map scale",
      "terrain_segmentation": 1,
    
      "_water_comment":
      [
        "Multiplier for water 'coverage' - higher increases the water level.",
        "Water level = 10 * log2(this value)"
      ],
      "water": 1,
    
      "_comment_width+height": "Width and height of map, in tiles; 0 means infinite",
      "width": 0,
      "height": 32,
    
      "_starting_area_comment": "Multiplier for 'biter free zone radius'",
      "starting_area": 1,
    
      "peaceful_mode": false,
    
      "autoplace_controls":
      {
        "coal": {"frequency": 1, "size": 1, "richness": 1},
        "stone": {"frequency": 1, "size": 1, "richness": 1},
        "copper-ore": {"frequency": 1, "size": 1,"richness": 1},
        "iron-ore": {"frequency": 1, "size": 1, "richness": 1},
        "uranium-ore": {"frequency": 1, "size": 1, "richness": 1},
        "crude-oil": {"frequency": 1, "size": 1, "richness": 1},
        "trees": {"frequency": 1, "size": 1, "richness": 1},
        "enemy-base": {"frequency": 1, "size": 1, "richness": 1}
      },
    
      "cliff_settings":
      {
        "_name_comment": "Name of the cliff prototype",
        "name": "cliff",
    
        "_cliff_elevation_0_comment": "Elevation of first row of cliffs",
        "cliff_elevation_0": 10,
    
        "_cliff_elevation_interval_comment": "Elevation difference between successive rows of cliffs",
        "cliff_elevation_interval": 10,
    
        "_richness_comment": "Multiplier for cliff continuity; 0 will result in no cliffs, 10 will make all cliff rows completely solid",
        "richness": 1
      },
    
      "_property_expression_names_comment":
      [
        "Overrides for property value generators",
        "Elevation influences water and cliff placement.",
        "Leave it blank to get 'normal' terrain.",
        "Use '0_16-elevation' to reproduce terrain from 0.16.",
        "Use '0_17-island' to get an island."
      ],
      "property_expression_names":
      {
        "elevation": "0_17-island",
    
        "control-setting:aux:bias": "0.300000",
        "control-setting:aux:frequency:multiplier": "1.333333",
        "control-setting:moisture:bias": "0.100000",
        "control-setting:moisture:frequency:multiplier": "0.500000"
      },
    
      "starting_points":
      [
        {"x": 1000, "y": 2000}
      ],
  
      "_seed_comment": "Use null for a random seed, number for a specific seed.",
      "seed": null
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-clusterio-client-22222
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio-clusterio-client-22222
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio-clusterio-client-22222
    spec:
      volumes:
        - name: factorio-clusterio-client-volume-22222
          persistentVolumeClaim:
            claimName: factorio-clusterio-persistent-storage-client-22222
        - name: factorio-clusterio-config-volume-22222
          configMap:
            name: factorio-clusterio-configmap-22222
      containers:
        - name: factorio-clusterio-client-22222
          image: mcweezel/factorio-clusterio:latest
          command:
            - sh 
            - -c 
            - "if ! [ -f /factorio/factorioClusterio ]; then cp -a /opt/factorioClusterio /factorio/factorioClusterio && cd /factorio/factorioClusterio && cp /data/config/config.json config.json && node client.js manage shared mods add clusterio && node client.js start instance && cp /data/config/server-settings.json instances/instance/server-settings.json && cp /data/config/map-gen-settings.json instances/instance/map-gen-settings.json && cp /data/config/instanceconfig.json instances/instance/config.json && rm instances/instance/saves/* && /opt/factorio/bin/x64/factorio --create instances/instance/saves/mysave.zip --map-gen-settings /data/config/map-gen-settings.json; fi && sleep 8000001; exec node client.js"
          imagePullPolicy: Always
          ports:
            - name: game-port
              containerPort: 34197
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - mountPath: /factorio
              name: factorio-clusterio-client-volume-22222
            - name: factorio-clusterio-config-volume-22222
              mountPath: /data/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-clusterio-persistent-storage-client-22222
  labels:
    app: factorio-clusterio-client-22222
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: factorio-clusterio-client-22222
spec:
  type: NodePort
  selector:
    app: factorio-clusterio-client-22222
  ports:
  - protocol: UDP
    port: 34197
