---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-clusterio
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio-clusterio
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio-clusterio
    spec:
      volumes:
        - name: factorio-clusterio-persistent-storage
          persistentVolumeClaim:
            claimName: factorio-clusterio-pv-claim
      containers:
        - name: factorio-clusterio
          image: mcweezel/factorio-clusterio:latest
          imagePullPolicy: Always
          ports:
            - name: game-port
              containerPort: 34197
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - mountPath: /factorio-clusterio
              name: factorio-clusterio-persistent-storage
