---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-clusterio-pv-claim
  labels:
    app: factorio-clusterio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
