---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pv-claim
  labels:
    app: factorio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
