---
kind: Service
apiVersion: v1
metadata:
  name: factorio-clusterio-service
spec:
  type: NodePort
  selector:
    app: factorio-clusterio
  ports:
  - protocol: UDP
    port: 34197
    nodePort: 30001
